server:
  port: 7101


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: provider-service

feign:
  hystrix:
    enabled: true
#provider-service:
#  ribbon:
#    key: value

logging:
  config: classpath:logback.xml
