server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: zuul-service

###localhost:8080/harvey/hallapi/halls/
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  prefix: /harvey/
  routes:
    harvey-user:
      path: /userapi/**
      serviceId: user-service
##是否允许重试  饥汉模式  预加载
      retryable: true
    harvey-cinema:
      path: /cinemaapi/**
      serviceId: cinema-service
      retryable: true
    harvey-film:
      path: /filmapi/**
      serviceId: film-service
      retryable: true
    harvey-hall:
      path: /hallapi/**
      serviceId: hall-service
      retryable: true

    #  routes:
    ###定义转发服务规则（随便起名）
#    hall-service:
      ###以/api-member/访问转发到会员服务
#      path: /apihall/**
  ###Zuul默认会过滤一些头信息，需要过滤设置。限制属性不到转发服务header头  只限制test


#  sensitive-headers: "test"
#      serviceId: hall-service


#  ignoredServices: '*'  禁用serviceid


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#Ribbon相关配置
#  ribbon.ConnectTimeout=250
#  ribbon.ReadTimeout=1000
#  ribbon.OkToRetryOnAllOperations=true
#  ribbon.MaxAutoRetries=0
#  ribbon.MaxAutoRetriesNextServer=1

logging:
  config: classpath:logback.xml
