mybatis-plus:
  mapper-locations: classpath*:com/example/kaidun/**/xml/*Mapper.xml
  #  src/main/java/com/example/meetingfilm/backend/common
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

server:
  port: 8803

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: harvey
    filters: log4j,wall,mergeStat
#    datasource:
#      url: jdbc:oracle:thin:@10.0.1.12:1521:DB2
#      username: PROD5516
#      password: ILoveKD
#      filters: log4j,wall,mergeStat
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#    jpa:
#      database: oracle
#      show-sql: true

  logging:
    config: classpath:logback.xml
